# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

env:
  # Faucet
  CONTRACT_ADDRESS_FAUCET: ${{ secrets.CONTRACT_ADDRESS_FAUCET }}
  FAUCET_PROVIDER: ${{ secrets.FAUCET_PROVIDER }}
  FAUCET_SIGNER: ${{ secrets.FAUCET_SIGNER }}
  CAPTCHA_SECRET: ${{secrets.CAPTCHA_SECRET}}

  # Mint
  SIGNER_KEY: ${{secrets.SIGNER_KEY}}
  CONTRACT_ADDRESS_NFT: ${{secrets.CONTRACT_ADDRESS_NFT}}

  # Discord
  GUILD_ID: ${{secrets.GUILD_ID}}

  # Generation
  GENERATION_PASSWORD: ${{secrets.GENERATION_PASSWORD}}
  SUBGRAPH_URL: ${{secrets.SUBGRAPH_URL}}

  # Prod Database
  MONGO_URI_PROD: ${{secrets.MONGO_URI_PROD}}

  # Dev Database
  MONGO_URI_DEV: ${{secrets.MONGO_URI_DEV}}

  # Test Database
  MONGO_URI_TEST: ${{secrets.MONGO_URI_TEST}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run test
